### ISSUE TITLE
remove link to pr in comments?

### ISSUE THREAD

**Issue by mo271** [leanprover-community/mathlib-port-status#4]
Currently in the table  in "In progress files" we have the link to the mathlib4 pr twice:
once in the column "pr" and once in the column "comments"
Might it be a good idea to remove it from the "comments" column?

**Comment by eric-wieser** [comment]
This information is in the comments column because when `mathlibtools` parses the yaml file it reports it as a comment.
So the fix to this would go in mathlibtools.

**Comment by eric-wieser** [comment]
Fixed in 10e7f51139abf008d3a584aca5eca4851876ed37 by using the new datasource
